### PR TITLE
Doc fixes round 2

### PR DESCRIPTION
**Pull request by chmanie**
> ⚠️  NOTE: Please don't use the PR description for communication, use comments instead.

Please add all your doc fixes here

- [x] Fix Links to ContractClient doc page

- [x] Add table of authority to AuthorityClient API

- [x] Add task roles permissions table to docs

### CODE REVIEW

**Comment by chmanie** [comment]
@gichiba I added another task for you :)

**Comment by gichiba** [comment]
Ha! I removed it because I actually reviewed the overview doc and it seems pretty explicitly clear here:
https://docs.colony.io/colonyjs/docs-contractclient/

**Comment by chmanie** [comment]
Fair enough!

**Comment by chmanie** [comment]
Shall we, can we?

**Comment by gichiba** [comment]
We can!

**Pull request merged**
