### PR TITLE
Fix wrong role conceptions in documentation

### PR DESCRIPTION
**Pull request by fallafeljan**
## Description
`role` specifies the role that gets rated/revealed, not the role that submits/reveals the rating — it was wrongly stated before. The evaluator, however, can be specified via `setTaskRoleUser`. The user who submits/reveals her or his rating for the worker needs to be specified in that role.

### CODE REVIEW

**Comment by gichiba** [comment]
I don't know if my commit is necessary or not, but I think that the changes made in _API_ColonyClient will be overwritten if they're not also changed in the client code comments. Also, my hooks are broken so I had to commit with `--no-verify` -- I hope that's ok...

**Comment by fallafeljan** [comment]
Good point, I didn’t think about the generation!

**Comment by chmanie** [comment]
Oops. Didn't catch that. Thanks @gichiba

**Comment by chmanie** [comment]
Also @fallafeljan that means that you also didn't run the precommit hooks (as the docs should be built on commit).

**Comment by gichiba** [comment]
Ah, this probably means that "Improve this doc" isn't really that effective for any of the API docs huh?

**Comment by chmanie** [comment]
Yeah, good point, Griffin. But for that we can probably just do it like this time. It’s an easy way to point out errors, just like Jan did.

**Comment by fallafeljan** [comment]
Couldn't we move (or: expand) generation of documentation to CI?

**Comment by chmanie** [comment]
> Couldn't we move (or: expand) generation of documentation to CI?

Yes that certainly is possible. Want to open an issue in the backlog?

**Comment by fallafeljan** [comment]
This PR is becoming somewhat stale, shall we merge it? I can't do it by myself.

**Comment by chmanie** [comment]
Oh, yeah sure. If you rebase it, I'll merge it!

**Pull request merged**
